In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path= '/content/drive/MyDrive/dataset_x/test.csv'
# the previous path is of the test data, i want to pre-process before sending to the model for prediction
#I had used the same path for train data preprocessing
df = pd.read_csv(path)

In [ ]:
df

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,NaN,NaN,6142
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,[QUALITY GUARANTEED: Luxury cozy plush polyest...,<b>DCGARING Throw Blanket</b><br><br> <b>Size ...,1622
2,1871949,I-Match Auto Parts Front License Plate Bracket...,"[Front License Plate Bracket Made Of Plastic,D...",Replacement for The Following Vehicles:2020 LE...,7540
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,[Available as a single item or bulk packed. Se...,Our Excellence in Service Lapel Pins feature a...,12442
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",NaN,NaN,6318
...,...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",[Brightly colored pet sweatshirts with authent...,"ZA6015 16 43 Size-See Chart Below: Medium: 16""...",7073
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,NaN,NaN,1
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,"[8-Inch centers,1/2-Inch IPS inlets,9-Inch spo...",39135001 Features: -ADA compliant. -Includes p...,10645
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,"[Indoor or outdoor aluminum artwork prints,8 i...",Features. Great for inside or outside these Al...,12680
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,[Engineered and Manufactured Under European St...,Our Remanufactured Replacement Lexmark Ink Car...,0

In [ ]:
df2= df

In [ ]:
df2['TITLE']= df2['TITLE'].fillna('')+ df2['BULLET_POINTS'].fillna('') + df2['DESCRIPTION'].fillna('')
# IMPORTANT: IF YOU WANT TO USE TEST DATA TO PREPROCESS THE CODE IS FINE, HOWEVER FOR TRAINING PLEASE UNCOMMENT THE BELOW CODE
# df2= df2.drop(labels= ['BULLET_POINTS','DESCRIPTION'],axis=1)

In [ ]:
df2
num_empty = (df2['TITLE'] == '').sum()
print(f"Number of empty strings in 'my_column': {num_empty}")

Number of empty strings in 'my_column': 3

In [ ]:
df2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318
...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0

***WARNING!!! THE BELOW COMMENTED SECTION OF CODE WAS ONLY APPLICABLE FOR TRAINING DATA, PLEASE DON'T UNCOMMENT TO USE ON TEST DATA, U CAN CONTINUE WITHOUT UNCOMMENTING, IF U WANT TO PREPROCESS ONLY THE TEST DATA***

In [ ]:
#type_counts = df.groupby('PRODUCT_TYPE_ID')['PRODUCT_ID'].count()


#top_count = int(type_counts.quantile(q=0.99))

# get the list of PRODUCT_TYPE_ID that meet the condition
#type_list = type_counts[type_counts >= top_count].index.tolist()

# filter the original dataframe to keep only the rows with PRODUCT_TYPE_ID in type_list
#filtered_df = df2[df2['PRODUCT_TYPE_ID'].isin(type_list)]

# print the resulting dataframe
#print(filtered_df)

#print(len(type_list))

        PRODUCT_ID                                              TITLE  \
7           938007  Pokemon M-037 Kyurem Figure Monster Collection...
9          1609597  Lug Women's Puddle Jumper Wheelie 2, Heather G...
12         2217122  Mon journal intime licorne: Idée de cadeau pou...
18          308161                  The Works of Samuel Johnson, LL.D
22         1167211  The Pillow Collection P18-PT-ANISHA-STONE-L55C...
...            ...                                                ...
734729     1361018  Universal Air Conditioner KT 4773A A/C Compres...
734730     1821370  Christopher Knight Home Nalany Throw Pillow (S...
734732     2456362  Dive Log Book: Scuba Diving Logbook for Beginn...
734734     1190194  Caroline's Treasures BB1801DS812 Halloween Bas...
734735     1040810  Amsahr 18C1623 Lexmark X3530 Remanufactured Re...

        PRODUCT_TYPE_ID
7                     0
9                  2640
12                    1
18                 6104
22                 7258
...                 ...
734729             7254
734730             8501
734732                1
734734            12680
734735                0

[337033 rows x 3 columns]
107

In [ ]:
#df3 = filtered_df
df3=df2

In [ ]:
df2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318
...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0

In [ ]:
import pandas as pd
import re
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')


# Define a regular expression to extract the size information
size_regex = r"\b(\d+(?:\.\d+)?[\s\w]*?(?:UK)?[\s\d]*?)(?![^()]*\))\b"

# Create a WordNetLemmatizer object for lemmatization
wnl = WordNetLemmatizer()

# Define a function to lemmatize a given text
def lemmatize_text(text):
    # Tokenize the text into words
    words = nltk.word_tokenize(text)
    # Lemmatize each word and join them back into a string
    return ' '.join([wnl.lemmatize(word) for word in words])

# Extract size information from the 'TITLE' column using the regular expression
df3['SIZE_INFO'] = df3['TITLE'].str.findall(size_regex).apply(' '.join)

# Lemmatize the 'SIZE_INFO' column
df3.loc[:, 'LEM_SIZE_INFO'] = df3['SIZE_INFO'].apply(lemmatize_text)

# Remove the 'SIZE_INFO' column
df3.drop(columns=['SIZE_INFO'], inplace=True)

# Print the resulting dataframe
print(df3)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

        PRODUCT_ID                                              TITLE  \
0           604373  Manuel d'Héliogravure Et de Photogravure En Re...
1          1729783  DCGARING Microfiber Throw Blanket Warm Fuzzy P...
2          1871949  I-Match Auto Parts Front License Plate Bracket...
3          1107571  PinMart Gold Plated Excellence in Service 1 Ye...
4           624253  Visual Mathematics, Illustrated by the TI-92 a...
...            ...                                                ...
734731      921419  Casual Canine Basic Hoodie for Dogs, 16" Mediu...
734732     2456362  Dive Log Book: Scuba Diving Logbook for Beginn...
734733      841529  Axor 39135001 Citterio Widespread Faucet with ...
734734     1190194  Caroline's Treasures BB1801DS812 Halloween Bas...
734735     1040810  Amsahr 18C1623 Lexmark X3530 Remanufactured Re...

        PRODUCT_TYPE_ID                                      LEM_SIZE_INFO
0                  6142
1                  1622         40 39 49 49 59 49 79 59 79 100 39 49 49 59
2                  7540  2018 2020 5211478170 5211478170 2020 2020 2019...
3                 12442                                    1 5 3mm 3 4 3mm
4                  6318                                              92 89
...                 ...                                                ...
734731             7073                             16 16 43 16 8 12 16 20
734732                1
734733            10645  39135001 8 1 2 9 5 1 2 90 1 1 8 39135001 9 7.8...
734734            12680                            8HX12W 8 12 8 0.02 12 1
734735                0                  18C1623 9001 9001 18C1623 18C1623

[734736 rows x 4 columns]

In [ ]:
df3.to_csv('t1.csv', index=False)

In [ ]:
f1= pd.read_csv('/content/t1.csv')

In [ ]:
f1

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,LEM_SIZE_INFO
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,NaN
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40 39 49 49 59 49 79 59 79 100 39 49 49 59
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018 2020 5211478170 5211478170 2020 2020 2019...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1 5 3mm 3 4 3mm
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92 89
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16 16 43 16 8 12 16 20
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,NaN
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001 8 1 2 9 5 1 2 90 1 1 8 39135001 9 7.8...
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8HX12W 8 12 8 0.02 12 1
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18C1623 9001 9001 18C1623 18C1623

In [ ]:
pattern = r'\d+\.?\d*'

# Create a new column "SIZE_NUM" to store the numerical values
f1['SIZE_NUM'] = f1['LEM_SIZE_INFO'].apply(lambda x: ' '.join([str(float(s)) for s in re.findall(pattern, str(x))]))

# Remove the "LEM_SIZE_INFO" column
f1 = f1.drop(columns=['LEM_SIZE_INFO'])

In [ ]:
f1

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [ ]:
import pandas as pd

In [ ]:
f1.to_csv('t2.csv', index=False)

NameError: ignored

In [ ]:
f2 = pd.read_csv("/content/t2.csv")

In [ ]:
f2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,NaN
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,NaN
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [ ]:
f2['SIZE_NUM'] = f2['SIZE_NUM'].fillna('0')

In [ ]:
f2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [ ]:
f2['PRODUCT_TYPE_ID'] = f2['PRODUCT_TYPE_ID'].astype('category')

In [ ]:
f2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [ ]:
import numpy as np

In [ ]:
f2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

**WARNING!!: THE BELOW COMMENTED CODE ONLY APPLIES TO DROPPING TRAINING NAN DATA, PLEASE DONT UNCOMMENT TO USE ON TESTDATA**

In [ ]:
#f2 = f2[~(f2['SIZE_VEC'].apply(lambda x: x[0]).isna())] # removes nan

In [ ]:
f2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734728,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734729,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0
734730,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734731,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734732,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [ ]:
f2.to_csv('t3.csv', index=False)

In [ ]:
import pandas as pd

In [44]:
f3 = pd.read_csv("/content/t3.csv")

In [ ]:
import pandas as pd
import re
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [45]:
f3

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [46]:
df23=f3

In [47]:
df23

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,40.0 39.0 49.0 49.0 59.0 49.0 79.0 59.0 79.0 1...
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,2018.0 2020.0 5211478170.0 5211478170.0 2020.0...
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,1.0 5.0 3.0 3.0 4.0 3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,92.0 89.0
...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,16.0 16.0 43.0 16.0 8.0 12.0 16.0 20.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,39135001.0 8.0 1.0 2.0 9.0 5.0 1.0 2.0 90.0 1....
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,8.0 12.0 8.0 12.0 8.0 0.02 12.0 1.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,18.0 1623.0 9001.0 9001.0 18.0 1623.0 18.0 1623.0

In [48]:
df23['SIZE_NUM'] = df23['SIZE_NUM'].apply(lambda x: [float(i) for i in str(x).split()])

# sort the SIZE_NUM column in descending order
df23['SIZE_NUM'] = df23['SIZE_NUM'].apply(lambda x: sorted(x, reverse=True))

# create new columns with the top 3 values, filling with 0 if there are less than 3
df23['SIZE_NUM_1'] = df23['SIZE_NUM'].apply(lambda x: x[0] if len(x) >= 1 else 0)
df23['SIZE_NUM_2'] = df23['SIZE_NUM'].apply(lambda x: x[1] if len(x) >= 2 else 0)
df23['SIZE_NUM_3'] = df23['SIZE_NUM'].apply(lambda x: x[2] if len(x) >= 3 else 0)

# drop the original SIZE_NUM column
df23.drop('SIZE_NUM', axis=1, inplace=True)

In [49]:
df23

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM_1,SIZE_NUM_2,SIZE_NUM_3
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,6142,0.000000e+00,0.000000e+00,0.0
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,1622,1.000000e+02,7.900000e+01,79.0
2,1871949,I-Match Auto Parts Front License Plate Bracket...,7540,5.211478e+09,5.211478e+09,2020.0
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,12442,5.000000e+00,4.000000e+00,3.0
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",6318,9.200000e+01,8.900000e+01,0.0
...,...,...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",7073,4.300000e+01,2.000000e+01,16.0
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,1,0.000000e+00,0.000000e+00,0.0
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,10645,3.913500e+07,3.913500e+07,90.0
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,12680,1.200000e+01,1.200000e+01,12.0
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0,9.001000e+03,9.001000e+03,1623.0

In [85]:

from catboost import CatBoostRegressor

In [93]:
path_model= '/content/catboost_model'
#THIS IS THE PATH OF MODEL I TRAINED,PLEASE USE FIND MODEL GIVEN IN ZIP FILE WHICH I MADE
model.load_model(path_model)
# LOADING A MODEL TRAINED ON THE DATA PROVIDED

THIS WAS THE CODE OF THE MODEL I TRAINED [model = CatBoostRegressor(loss_function='MAPE', random_seed=42, iterations=1000, learning_rate=0.91, depth=6, verbose=100)
model.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_test, y_test), early_stopping_rounds=50, use_best_model=True)]

In [87]:
df2=df23
df2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM_1,SIZE_NUM_2,SIZE_NUM_3,PRODUCT_LENGTH
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,0.489825,1.000000e+00,1.000000e+00,1.0,454.000004
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,0.142546,1.010000e+02,8.000000e+01,80.0,293.999988
2,1871949,I-Match Auto Parts Front License Plate Bracket...,0.601041,5.211478e+09,5.211478e+09,2021.0,293.999988
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,0.934879,6.000000e+00,5.000000e+00,4.0,427.396692
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",0.505632,9.300000e+01,9.000000e+01,1.0,427.396692
...,...,...,...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",0.564505,4.400000e+01,2.100000e+01,17.0,293.999988
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,0.000095,1.000000e+00,1.000000e+00,1.0,454.000004
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,0.809655,3.913500e+07,3.913500e+07,91.0,293.999988
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,0.950781,1.300000e+01,1.300000e+01,13.0,293.999988
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0.000000,9.002000e+03,9.002000e+03,1624.0,293.999988

In [88]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df2['PRODUCT_TYPE_ID'] = encoder.fit_transform(df2['PRODUCT_TYPE_ID']) / len(encoder.classes_)

In [89]:
df2

,PRODUCT_ID,TITLE,PRODUCT_TYPE_ID,SIZE_NUM_1,SIZE_NUM_2,SIZE_NUM_3,PRODUCT_LENGTH
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,0.489825,1.000000e+00,1.000000e+00,1.0,454.000004
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,0.142546,1.010000e+02,8.000000e+01,80.0,293.999988
2,1871949,I-Match Auto Parts Front License Plate Bracket...,0.601041,5.211478e+09,5.211478e+09,2021.0,293.999988
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,0.934879,6.000000e+00,5.000000e+00,4.0,427.396692
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",0.505632,9.300000e+01,9.000000e+01,1.0,427.396692
...,...,...,...,...,...,...,...
734731,921419,"Casual Canine Basic Hoodie for Dogs, 16"" Mediu...",0.564505,4.400000e+01,2.100000e+01,17.0,293.999988
734732,2456362,Dive Log Book: Scuba Diving Logbook for Beginn...,0.000095,1.000000e+00,1.000000e+00,1.0,454.000004
734733,841529,Axor 39135001 Citterio Widespread Faucet with ...,0.809655,3.913500e+07,3.913500e+07,91.0,293.999988
734734,1190194,Caroline's Treasures BB1801DS812 Halloween Bas...,0.950781,1.300000e+01,1.300000e+01,13.0,293.999988
734735,1040810,Amsahr 18C1623 Lexmark X3530 Remanufactured Re...,0.000000,9.002000e+03,9.002000e+03,1624.0,293.999988

In [90]:
X = df2[['PRODUCT_TYPE_ID', 'SIZE_NUM_1', 'SIZE_NUM_2', 'SIZE_NUM_3']]
X['PRODUCT_TYPE_ID'] = X['PRODUCT_TYPE_ID'].astype(str)

<ipython-input-90-59cd357e82d4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['PRODUCT_TYPE_ID'] = X['PRODUCT_TYPE_ID'].astype(str)

In [91]:
y_pred = model.predict(X)

In [92]:
y_pred

array([454.00000388, 293.99998829, 293.99998829, ..., 293.99998829,
       293.99998829, 293.99998829])

In [71]:
df2['PRODUCT_LENGTH'] = y_pred

In [72]:
df2[['PRODUCT_ID', 'PRODUCT_LENGTH']].to_csv('predicted_lengths2.csv', index=False)

In [ ]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting catboost
  Downloading catboost-1.1.1-cp39-none-manylinux1_x86_64.whl (76.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 12.8 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.9/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.9/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.9/dist-packages (from catboost) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from catboost) (1.10.1)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.9/dist-packages (from catboost) (5.13.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.24.0->catboost) (2022.7.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (8.4.0)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (5.12.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (23.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (4.39.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from plotly->catboost) (8.2.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=3.2.0->matplotlib->catboost) (3.15.0)
Installing collected packages: catboost
Successfully installed catboost-1.1.1